#!/usr/bin/env bash
# A bash scripts that create a user, give necessary permissions

CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';
FLUST PRIVILEGES;